export const expensesCategories = [
  { id: 0, name: 'Groceries', class: 'fas fa-cookie-bite', color: '#fd7e14'},
  { id: 1, name: 'Eating Out', class: 'fas fa-utensils', color: '#be4bdb'},
  { id: 2, name: 'Leisure', class: 'fas fa-ticket-alt', color: '#4c6ef5'},
  { id: 3, name: 'Transport', class: 'fas fa-subway', color: '#15aabf'},
  { id: 4, name: 'Auto', class: 'fas fa-truck-pickup', color: '#f783ac'},
  { id: 5, name: 'Bills', class: 'fas fa-file-invoice-dollar', color: '#82c91e'},
  { id: 6, name: 'Beauty', class: 'fas fa-spa'},
  { id: 7, name: 'Books', class: 'fas fa-book'},
  { id: 8, name: 'Childcare', class: 'fas fa-baby-carriage'},
  { id: 9, name: 'Clothing', class: 'fas fa-socks'},
  { id: 10, name: 'Family', class: 'fas fa-hand-holding-heart'},
  { id: 11, name: 'Games', class: 'fas fa-gamepad'},
  { id: 12, name: 'Gifts', class: 'fas fa-gift'},
  { id: 13, name: 'Home', class: 'fas fa-home'},
  { id: 14, name: 'Health', class: 'fas fa-home'},
  { id: 15, name: 'Electronics', class: 'fas fa-plug'},
  { id: 16, name: 'Education', class: 'fas fa-user-graduate'},
  { id: 17, name: 'Insurance', class: 'fas fa-user-shield'},
  { id: 18, name: 'Mobile', class: 'fas fa-mobile-alt'},
  { id: 19, name: 'Pets', class: 'fas fa-cat"'},
  { id: 20, name: 'Sport', class: 'fas fa-biking'},
  { id: 21, name: 'Taxes', class: 'fas fa-file-invoice'},
  { id: 22, name: 'Vacation', class: 'fas fa-plane'},
  { id: 23, name: 'Other', class: 'fas fa-coins'}
]
