export const expencesCategories = [
  { name: 'Groceries', class: 'fas fa-cookie-bite', color: '#fd7e14'},
  { name: 'Eating Out', class: 'fas fa-utensils', color: '#be4bdb'},
  { name: 'Leisure', class: 'fas fa-ticket-alt', color: '#4c6ef5'},
  { name: 'Transport', class: 'fas fa-subway', color: '#15aabf'},
  { name: 'Auto', class: 'fas fa-truck-pickup', color: '#f783ac'},
  { name: 'Bills', class: 'fas fa-file-invoice-dollar', color: '#82c91e'},
  { name: 'Beauty', class: 'fas fa-spa'},
  { name: 'Books', class: 'fas fa-book'},
  { name: 'Childcare', class: 'fas fa-baby-carriage'},
  { name: 'Clothing', class: 'fas fa-socks'},
  { name: 'Family', class: 'fas fa-hand-holding-heart'},
  { name: 'Games', class: 'fas fa-gamepad'},
  { name: 'Gifts', class: 'fas fa-gift'},
  { name: 'Home', class: 'fas fa-home'},
  { name: 'Health', class: 'fas fa-home'},
  { name: 'Electronics', class: 'fas fa-plug'},
  { name: 'Education', class: 'fas fa-user-graduate'},
  { name: 'Insurance', class: 'fas fa-user-shield'},
  { name: 'Mobile', class: 'fas fa-mobile-alt'},
  { name: 'Pets', class: 'fas fa-cat"'},
  { name: 'Sport', class: 'fas fa-biking'},
  { name: 'Taxes', class: 'fas fa-file-invoice'},
  { name: 'Vacation', class: 'fas fa-plane'},
  { name: 'Other', class: 'fas fa-coins'}
]
export const incomingsCategories = [
  { name: 'Salary', class: 'fas fa-money-bill'},
  { name: 'Freelance', class: 'fas fa-laptop"'},
  { name: 'Investments', class: 'fas fa-briefcase'},
  { name: 'Dividents', class: 'fas fa-seedling'},
  { name: 'Awards', class: 'fas fa-trophy'},
  { name: 'Rental', class: 'fas fa-home'},
  { name: 'Other', class: 'fas fa-coins'}
]
